apiVersion: apps/v1
kind: Deployment
metadata:
  name: uenrner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uenrner
  template:
    metadata:
      labels:
        app: uenrner
    spec:
      containers:
      - image: okteto.dev/uenrner:latest
        name: uenrner
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/GoidFood-html.zip"
        - name: Vless_UUID
          value: "4747e11e-7181-4114-acc2-e306a7ccfc60"
        - name: Vless_Path
          value: "/4747e11e-7181-4114-acc2-e306a7ccfc60-vless"
        - name: Vmess_UUID
          value: "4747e11e-7181-4114-acc2-e306a7ccfc60"
        - name: Vmess_Path
          value: "/4747e11e-7181-4114-acc2-e306a7ccfc60-vmess"
        - name: Share_Path
          value: "/zzedfk"